config/routes.rb
Rails.application.routes.draw do
  resources :menu_items_orders
  resources :orders
  resources :menus
  resources :menu_items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/about', to: 'static_pages#about'
  root "menus#index"



end

app/models/menu.rb
class Menu < ApplicationRecord
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_params
      params.require(:menu).permit(:name, :imageUrl, :price, :description)
    end
end

class OrdersController < ApplicationController
    before_action :set_order, only: [:show, :edit, :update, :destroy]
    
    # GET /orders
    # GET /orders.json
    def index
        @orders = Order.all
    end
    
    # GET /orders/1
    # GET /orders/1.json
    def show
    end
    
    # GET /orders/new
    def new
        @order = Order.new
    end
    
    # GET /orders/1/edit
    def edit
    end
    
    # POST /orders
    # POST /orders.json
    def create
        @order = Order.new(order_params)
        
        respond_to do |format|
            if @order.save
                format.html { redirect_to @order, notice: 'Order was successfully created.' }
                format.json { render :show, status: :created, location: @order }
                else
                format.html { render :new }
                format.json { render json: @order.errors, status: :unprocessable_entity }
            end
        end
    end
    
    # PATCH/PUT /orders/1
    # PATCH/PUT /orders/1.json
    def update
        respond_to do |format|
            if @order.update(order_params)
                format.html { redirect_to @order, notice: 'Order was successfully updated.' }
                format.json { render :show, status: :ok, location: @order }
                else
                format.html { render :edit }
                format.json { render json: @order.errors, status: :unprocessable_entity }
            end
        end
    end
    
    # DELETE /orders/1
    # DELETE /orders/1.json
    def destroy
        @order.destroy
        respond_to do |format|
            format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
            format.json { head :no_content }
        end
    end
    
    private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
        @order = Order.find(params[:id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
        params.require(:order).permit(:customer_name)
    end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.erb
<%= form_with(model: menu, local: true) do |form| %>
  <% if menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :menu_name %>
  </div>

  <div class="field">
    <%= form.label :imageUrl %>
    <%= form.text_field :imageUrl, id: :menu_imageUrl %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :menu_price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :menu_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<center>
<p id="notice"><%= notice %></p>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Imageurl</th>
<!-- 
      <th>Price</th>
 -->
<!-- 
      <th>Description</th>
 -->
      <th colspan="3"></th>
    </tr>
  </thead>


<p id="notice"><%= notice %></p>
<img src="http://410.keysasht.msu.domains/Trappasta.png">
<h1>Menus</h1>



  <tbody>
    <% @menus.each do |menu| %>
	
      <tr>
        <td><%= menu.name %></td>
<!-- 
        <td><%= menu.imageUrl %></td>
 -->
<!-- 
        <td><%= menu.price %></td>
 -->
        <td> <img src="<%= menu.imageUrl %>"  style="width:304px;height:228px;"></td>
<!--  -->
 <!-- 
       <td><%= menu.description %></td>
 -->
 
        <td><%= link_to 'Order', menu %></td>

<!--
        <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
        <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
 -->

      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Menu', new_menu_path %>
</center>

app/views/menus/new.html.erb
<h1>New Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @menu.name %>
  
  <h3>Remember This ID Number so you can place your order or ELSE!</h3>
  <h4><%= @menu.id %></h4>

</p>

<p>
  <img src="<%= @menu.imageUrl %>" >
</p>

<p>
  <strong>Price:</strong>
  <%= @menu.price / 100.00 %>
</p>

<p>
  <strong>Description:</strong>
  <%= @menu.description %>
</p>

<!-- 
<%= link_to 'Edit', edit_menu_path(@menu) %> |
 -->

<%= link_to 'Place Your Order', new_menu_items_order_path %>
 
<%= link_to 'Back', menus_path %>