config/routes.rb
Rails.application.routes.draw do
  resources :menu_items_orders
  resources :orders
  resources :menus
  resources :menu_items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/about', to: 'static_pages#about'
  root "menus#index"



end

app/models/menu_items_order.rb
class MenuItemsOrder < ApplicationRecord
end

app/controllers/menu_items_orders_controller.rb
class MenuItemsOrdersController < ApplicationController
  before_action :set_menu_items_order, only: [:show, :edit, :update, :destroy]

  # GET /menu_items_orders
  # GET /menu_items_orders.json
  def index
    @menu_items_orders = MenuItemsOrder.all
  end

  # GET /menu_items_orders/1
  # GET /menu_items_orders/1.json
  def show
  end

  # GET /menu_items_orders/new
  def new
    @menu_items_order = MenuItemsOrder.new
  end

  # GET /menu_items_orders/1/edit
  def edit
  end

  # POST /menu_items_orders
  # POST /menu_items_orders.json
  def create
    @menu_items_order = MenuItemsOrder.new(menu_items_order_params)

    respond_to do |format|
      if @menu_items_order.save
        format.html { redirect_to @menu_items_order, notice: 'Menu items order was successfully created.' }
        format.json { render :show, status: :created, location: @menu_items_order }
      else
        format.html { render :new }
        format.json { render json: @menu_items_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menu_items_orders/1
  # PATCH/PUT /menu_items_orders/1.json
  def update
    respond_to do |format|
      if @menu_items_order.update(menu_items_order_params)
        format.html { redirect_to @menu_items_order, notice: 'Menu items order was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu_items_order }
      else
        format.html { render :edit }
        format.json { render json: @menu_items_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_items_orders/1
  # DELETE /menu_items_orders/1.json
  def destroy
    @menu_items_order.destroy
    respond_to do |format|
      format.html { redirect_to menu_items_orders_url, notice: 'Menu items order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu_items_order
      @menu_items_order = MenuItemsOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_items_order_params
      params.require(:menu_items_order).permit(:menu_item_id, :order_id)
    end
end

app/helpers/menu_items_orders_helper.rb
module MenuItemsOrdersHelper
end

app/views/menu_items_orders/_form.html.erb
<%= form_with(model: menu_items_order, local: true) do |form| %>
  <% if menu_items_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu_items_order.errors.count, "error") %> prohibited this menu_items_order from being saved:</h2>

      <ul>
      <% menu_items_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :menu_item_id %>
    <%= form.number_field :menu_item_id, id: :menu_items_order_menu_item_id %>
  </div>

  <div class="field">
    <%= form.label :order_id %>
    <%= form.number_field :order_id, id: :menu_items_order_order_id %>
  </div>
  <div class="field">
    <%= form.label :credit %>
    <%= form.number_field :credit, id: :menu_items_order_credit %>
  </div>

  <div class="actions">
  	<p>If you mess up ordering you gotta start over!</p>
    <%= form.submit %>
  </div>
<% end %>

app/views/menu_items_orders/edit.html.erb
<h1>Editing Menu Items Order</h1>

<%= render 'form', menu_items_order: @menu_items_order %>

<%= link_to 'Show', @menu_items_order %> |
<%= link_to 'Back', menu_items_orders_path %>

app/views/menu_items_orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Menu Items Orders</h1>

<table>
  <thead>
    <tr>
      <th>Menu item</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menu_items_orders.each do |menu_items_order| %>
      <tr>
        <td><%= menu_items_order.menu_item_id %></td>
        <td><%= menu_items_order.order_id %></td>
        <td><%= link_to 'Show', menu_items_order %></td>
        <td><%= link_to 'Edit', edit_menu_items_order_path(menu_items_order) %></td>
        <td><%= link_to 'Destroy', menu_items_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu Items Order', new_menu_items_order_path %>

app/views/menu_items_orders/new.html.erb
<h1>New Menu Items Order</h1>

<%= render 'form', menu_items_order: @menu_items_order %>

<a href= "/">Home</a>

app/views/menu_items_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Menu item:</strong>
  <%= @menu_items_order.menu_item_id %>
</p>

<p>
  <strong>Order:</strong>
  <%= @menu_items_order.order_id %>
</p>


<a href= "/">Home</a>